spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring?autoReconnect=true&useUnicode=true&createDatabaseIfNotExist=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  type-aliases-package: com.lucky.springtransaction.pojo
  mapper-locations: classpath*:mapper/**/*.xml
  configuration:
    local-cache-scope: statement #每次查询都不走缓存，即清掉一级缓存

